# Generated by Django 2.1.7 on 2019-03-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='sex',
            field=models.IntegerField(choices=[(0, '男'), (1, '女')]),
        ),
    ]
