# Generated by Django 2.1.7 on 2019-03-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
