# Generated by Django 2.1.7 on 2019-03-05 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20190305_1439'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='woc',
        ),
    ]
