# Generated by Django 2.1.7 on 2019-03-05 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20190305_1444'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='aaaa',
        ),
    ]
