# Generated by Django 2.1.7 on 2019-03-05 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20190305_1446'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='aaaa',
            new_name='bbbb',
        ),
    ]
