# Generated by Django 2.1.7 on 2019-03-05 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_remove_meeting_creat_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='comment',
        ),
    ]
