# Generated by Django 2.1.7 on 2019-03-05 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_remove_meeting_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'verbose_name': '会议', 'verbose_name_plural': '会议'},
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='addtime',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='edittime',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='starttime',
        ),
    ]
