# Generated by Django 2.1.7 on 2019-03-05 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_auto_20190305_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='creat_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creat_person', to='management.user', verbose_name='管理员'),
        ),
    ]
