# Generated by Django 2.1.7 on 2019-03-05 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_meeting_starttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='addtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='comment',
            field=models.TextField(blank=True, default='备注为空', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='edittime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='endtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
